### ISSUE TITLE
这是为啥

### ISSUE THREAD

**Issue by linuxcpp6** [lyb88999/nkwspider#1]

**Comment by linuxcpp6** [comment]
> _No description provided._

**Comment by lyb88999** [comment]
应该是网页结构变了 某些地方需要重新改一下

**Comment by linuxcpp6** [comment]
> 应该是网页结构变了 某些地方需要重新改一下
确实改了

**Comment by lyb88999** [comment]
等我有时间了更新一下子

**Comment by linuxcpp6** [comment]
> 等我有时间了更新一下子

哈哈，快更新呀，新的获取时间获取不出来，内容也获取不了

**Comment by lyb88999** [comment]
对 刚刚看了一下确实是这样 哈哈

**Comment by lyb88999** [comment]
> 

兄弟你再试试行不行 没有打包依赖 我这里安的包太多了...

**Comment by linuxcpp6** [comment]
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接

**Comment by linuxcpp6** [comment]
这是要开dl吗

**Comment by lyb88999** [comment]
这个我没碰见过诶 哪一行代码报错了呀？

**Comment by linuxcpp6** [comment]
conn = connection.create_connection(
好的，我自己调试调试可能是我的python或者依赖版本过高

**Comment by linuxcpp6** [comment]
应该要搭建代理

**Comment by lyb88999** [comment]
兄弟留个联系方式 细说 按理来说不搭代理也可以的

**Comment by linuxcpp6** [comment]
哈哈，这里不方便留，我自己慢慢调，跳的了就用，调不了就不用

**Comment by linuxcpp6** [comment]
我知道怎么完了

**Comment by linuxcpp6** [comment]
玩

**Comment by lyb88999** [comment]
ok能用就行呢:)
